site_name: ""
site_url: https://sammusch.github.io/ds-garden/
repo_url: https://github.com/SamMusch/ds-garden
edit_uri: ""

extra_css:
  - stylesheets/extra.css
  - stylesheets/ad-sam.css
  - styles/heading-fold.css
  - styles/horiz-blocks.css

extra_javascript:
  - javascripts/ad-sam-copy.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/init-mermaid.js
  - javascripts/heading-fold.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

strict: false   # build warnings are okay; switch to true later

theme:
  name: material
  favicon: images/favicon.svg
  palette:
    primary: custom
  font:
    text: Mulish # Inter
    code: 'Greycliff CF' # "Nunito Sans"
  features:
    # - navigation.expand           # expands active section but allows collapse
    # - navigation.instant          # for state persistence
    - navigation.tracking         # highlights active heading in TOC
    - content.code.copy           # copy button on code blocks
    - toc.follow                  # right “On this page” follows scroll
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - bash
  custom_dir: overrides

plugins:
  - search
  - awesome-pages
  - roamlinks

#  - mermaid2:
#      arguments:
#        theme: default
#      javascript: https://unpkg.com/mermaid@10/dist/mermaid.esm.min.mjs

markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.mark
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
